# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(999, 678)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ln_search = QtWidgets.QLineEdit(Form)
        self.ln_search.setInputMask("")
        self.ln_search.setFrame(False)
        self.ln_search.setClearButtonEnabled(False)
        self.ln_search.setObjectName("ln_search")
        self.verticalLayout.addWidget(self.ln_search)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chosen = QtWidgets.QScrollArea(self.groupBox)
        self.chosen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chosen.setWidgetResizable(True)
        self.chosen.setObjectName("chosen")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 362, 266))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chosen.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.chosen)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.recommend = QtWidgets.QScrollArea(self.groupBox_2)
        self.recommend.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recommend.setWidgetResizable(True)
        self.recommend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.recommend.setObjectName("recommend")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 362, 265))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.recommend.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.recommend)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget_welcome = QtWidgets.QWidget(Form)
        self.widget_welcome.setObjectName("widget_welcome")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_welcome)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcome = QtWidgets.QLabel(self.widget_welcome)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.welcome.setFont(font)
        self.welcome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.verticalLayout_2.addWidget(self.welcome)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_welcome)
        font = QtGui.QFont()
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.widget_welcome)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Diamond Stocks"))
        self.ln_search.setPlaceholderText(_translate("Form", "Search"))
        self.groupBox.setTitle(_translate("Form", "Избранное"))
        self.groupBox_2.setTitle(_translate("Form", "Рекомендуемые"))
        self.welcome.setText(_translate("Form", "Добро пожаловать в приложение Diamond Stocks"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Данный проект реализован с помощью API от AlphaVantage.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Поэтому на приложение действует ограничение:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">нельзя совершать более 5 запросов в минуту, 500 запросов в день.</span></p></body></html>"))
