# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesave_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(604, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.filename = QtWidgets.QLineEdit(Form)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.save_excel = QtWidgets.QPushButton(Form)
        self.save_excel.setObjectName("save_excel")
        self.horizontalLayout_2.addWidget(self.save_excel)
        self.save_csv = QtWidgets.QPushButton(Form)
        self.save_csv.setObjectName("save_csv")
        self.horizontalLayout_2.addWidget(self.save_csv)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сохранение"))
        self.label.setText(_translate("Form", "Название файла:"))
        self.cancel.setText(_translate("Form", "Отмена"))
        self.save_excel.setText(_translate("Form", "Сохранить в Excel"))
        self.save_csv.setText(_translate("Form", "Сохранить в CSV"))
