# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ln_search = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_search.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ln_search.setInputMask("")
        self.ln_search.setFrame(False)
        self.ln_search.setClearButtonEnabled(False)
        self.ln_search.setObjectName("ln_search")
        self.horizontalLayout_2.addWidget(self.ln_search)
        self.button_search = QtWidgets.QPushButton(self.centralwidget)
        self.button_search.setText("")
        self.button_search.setObjectName("button_search")
        self.horizontalLayout_2.addWidget(self.button_search)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chosen = QtWidgets.QScrollArea(self.groupBox)
        self.chosen.setMaximumSize(QtCore.QSize(16777215, 450))
        self.chosen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chosen.setWidgetResizable(True)
        self.chosen.setObjectName("chosen")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 365, 328))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chosen.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.chosen)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.recommend = QtWidgets.QScrollArea(self.groupBox_2)
        self.recommend.setMaximumSize(QtCore.QSize(16777215, 450))
        self.recommend.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recommend.setWidgetResizable(True)
        self.recommend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.recommend.setObjectName("recommend")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 365, 328))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.recommend.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.recommend)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget_welcome = QtWidgets.QWidget(self.centralwidget)
        self.widget_welcome.setObjectName("widget_welcome")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_welcome)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcome = QtWidgets.QLabel(self.widget_welcome)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.welcome.setFont(font)
        self.welcome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.verticalLayout_2.addWidget(self.welcome)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_welcome)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.widget_welcome)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diamond Stocks"))
        self.ln_search.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.groupBox.setTitle(_translate("MainWindow", "Избранное"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Рекомендуемые"))
        self.welcome.setText(_translate("MainWindow", "Добро пожаловать в приложение Diamond Stocks"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Данный проект реализован с помощью бесплатного API от Finnhub.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Поэтому на приложение действуют такие ограничения:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">нельзя совершать более 60 запросов в минуту,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">а также нельзя получить информацию о некоторых компаниях.</span></p></body></html>"))
