# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(562, 496)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_request = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_request.setFont(font)
        self.label_request.setAlignment(QtCore.Qt.AlignCenter)
        self.label_request.setObjectName("label_request")
        self.verticalLayout.addWidget(self.label_request)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.results = QtWidgets.QWidget()
        self.results.setGeometry(QtCore.QRect(0, 0, 542, 449))
        self.results.setObjectName("results")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.results)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.results)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Результаты"))
        self.label_request.setText(_translate("Form", "Результаты поиска по запросу Apple"))
