# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updates_in_prices.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(357, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ticker = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.ticker.setFont(font)
        self.ticker.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ticker.setObjectName("ticker")
        self.horizontalLayout.addWidget(self.ticker)
        self.name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 32))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 31))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(0, 32))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 32))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 32))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lb_date = QtWidgets.QLabel(Form)
        self.lb_date.setObjectName("lb_date")
        self.gridLayout.addWidget(self.lb_date, 0, 1, 1, 1)
        self.lb_close = QtWidgets.QLabel(Form)
        self.lb_close.setObjectName("lb_close")
        self.gridLayout.addWidget(self.lb_close, 1, 1, 1, 1)
        self.lb_open = QtWidgets.QLabel(Form)
        self.lb_open.setObjectName("lb_open")
        self.gridLayout.addWidget(self.lb_open, 2, 1, 1, 1)
        self.lb_high = QtWidgets.QLabel(Form)
        self.lb_high.setObjectName("lb_high")
        self.gridLayout.addWidget(self.lb_high, 3, 1, 1, 1)
        self.lb_low = QtWidgets.QLabel(Form)
        self.lb_low.setObjectName("lb_low")
        self.gridLayout.addWidget(self.lb_low, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменения"))
        self.ticker.setText(_translate("Form", "TextLabel"))
        self.name.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "Прошлая дата:"))
        self.label_5.setText(_translate("Form", "open:"))
        self.label_7.setText(_translate("Form", "low:"))
        self.label_4.setText(_translate("Form", "close:"))
        self.label_6.setText(_translate("Form", "high:"))
        self.lb_date.setText(_translate("Form", "TextLabel"))
        self.lb_close.setText(_translate("Form", "TextLabel"))
        self.lb_open.setText(_translate("Form", "TextLabel"))
        self.lb_high.setText(_translate("Form", "TextLabel"))
        self.lb_low.setText(_translate("Form", "TextLabel"))
